# Generated by Django 3.0.4 on 2020-03-30 11:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='User', max_length=500, verbose_name='first name')),
                ('last_name', models.CharField(default='User', max_length=500, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('subject', multiselectfield.db.fields.MultiSelectField(choices=[('Pneumonia', 'Pn'), ('Diabetic', 'Di'), ('Hemorrhage', 'He')], max_length=29, verbose_name='subject')),
                ('img_to_detect', models.ImageField(null=True, upload_to='images', verbose_name='Drop Files')),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 3, 30, 11, 23, 27, 95554, tzinfo=utc), verbose_name='created date')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email')),
                ('result', models.CharField(max_length=200, null=True, verbose_name='result')),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 3, 30, 11, 23, 27, 95989, tzinfo=utc), null=True, verbose_name='result created date')),
            ],
        ),
    ]
