# Generated by Django 3.0.4 on 2020-03-31 13:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_auto_20200331_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 13, 58, 22, 104516, tzinfo=utc), verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='results',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 13, 58, 22, 105128, tzinfo=utc), null=True, verbose_name='result created date'),
        ),
    ]
